name: Java CI with Maven for Bug API tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Allure
      run: |
        wget -O allure-2.27.0.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
        unzip allure-2.27.0.zip
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
    - name: Test Execution
      run: mvn -B -f pom.xml clean test
    - name: Generate Allure Reports
      run: allure generate --single-file allure-results --clean -o allure-report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.EMAIL_SERVER_ADDRESS }}
        server_port: ${{ secrets.EMAIL_SERVER_PORT }}
        secure: true
        username: ${{ secrets.EMAIL_ADDRESS }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Github Actions job result
        to: cloud.user@loonycorn.com
        from: Loonycorn
        body: All the tests for ${{github.repository}} are completed!
        attachments: allure-report/index.html
